datasource:
  mysql:
    url: jdbc:mysql://localhost:3306/mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    username: hyeon
    password: hyeon
    
  postgresql:
    url: jdbc:postgresql://localhost:5434/postgresql
    driverClassName: org.postgresql.Driver
    username: hyeon
    password: hyeon
    
spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true